### ISSUE TITLE
Enhance handle_on_link_available_tags to consider Tags that are None

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/topology#106]
Hi,

I was running some tests and due to very specific conditions, the Link service tag metadata got empty, which led to the following error on topology:

```
2022-08-07 07:03:41,778 - ERROR [kytos.core.helpers] [helpers.py:151:handler_context_apm] (thread_pool_app_116) listen_to handler: <function Main.on_link_available_tags at 0x7f2adb48b9d0>, args: (<Main(topology, stopped 139821032920832)>, KytosEvent('kytos/mef_eline.link_available_tags', {'link': Link(Interface('SoL2-eth2', 2, Switch('00:00:00:00:00:00:00:13')), Interface('Ampath1-eth2', 2, Switch('00:00:00:00:00:00:00:11')))}, 0)) traceback: Traceback (most recent call last):,   File "/usr/local/lib/python3.9/dist-packages/kytos/core/helpers.py", line 146, in handler_context_apm,     result = handler(*args),   File "//var/lib/kytos/napps/kytos/topology/main.py", line 600, in on_link_available_tags,     self.handle_on_link_available_tags(event.content.get("link")),   File "//var/lib/kytos/napps/kytos/topology/main.py", line 608, in handle_on_link_available_tags,     values_a = [tag.value for tag in endpoint_a.available_tags],   File "//var/lib/kytos/napps/kytos/topology/main.py", line 608, in <listcomp>,     values_a = [tag.value for tag in endpoint_a.available_tags], AttributeError: 'NoneType' object has no attribute 'value',
```

I am aware that the issue was in the code which allowed the Link service tag metadata to be empty (which btw I've fixed), however... since the data model for Interface tags allows such a scenario, maybe we can enhance the Topology event handler to consider this case. Another option would be enhance Interface Tags to not allow None as a tag (which makes even more sense).

Just out of curiosity, it looks like MEF E-Line was kind of prepared for this possible error and [handled the metadata retrieval in a specific way](https://github.com/kytos-ng/mef_eline/blob/master/models/path.py#L44) (using `dict.get` method)

**Comment by italovalcy** [comment]
> @italovalcy, can we closed this since [kytos-ng/kytos#272](https://github.com/kytos-ng/kytos/pull/272) has landed?
> 
> The remaining `s_vlan` issue we can cover on [kytos-ng/mef_eline#203](https://github.com/kytos-ng/mef_eline/issues/203), OK? It's on our radar for `2022.3` version

Yes, sure thing!!
